"""initial schema

Revision ID: f87d3509a6dd
Revises: 
Create Date: 2026-07-19 11:41:03.416597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f87d3509a6dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('settings', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint("role IN ('admin','manager','employee')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_table('competencies',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_relevance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('version_major', sa.Integer(), nullable=False),
    sa.Column('version_minor', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('decomp_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint("status IN ('draft','under_review','active','deprecated')", name='ck_competencies_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('learning_strategy', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('mastery_threshold', sa.Float(), nullable=False),
    sa.Column('eval_dimensions', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint("learning_strategy IN ('conceptual','procedural','applied','analytical')", name='ck_skills_strategy'),
    sa.CheckConstraint('difficulty_level BETWEEN 1 AND 5', name='ck_skills_difficulty'),
    sa.CheckConstraint('hierarchy_level BETWEEN 1 AND 3', name='ck_skills_hierarchy'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skills_competency', 'skills', ['competency_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_mode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('prompt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_latency_ms', sa.Integer(), nullable=True),
    sa.Column('score_accuracy', sa.Float(), nullable=True),
    sa.Column('score_application', sa.Float(), nullable=True),
    sa.Column('score_reasoning', sa.Float(), nullable=True),
    sa.Column('score_consistency', sa.Float(), nullable=True),
    sa.Column('score_confidence', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('misconceptions', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('feedback_points', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('llm_model_used', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint("assessment_mode IN ('quiz','conversational','scenario','baseline')", name='ck_ar_mode'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ar_employee_skill', 'assessment_results', ['employee_id', 'skill_id'], unique=False)
    op.create_index('idx_ar_session', 'assessment_results', ['session_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('content_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interaction_prompts', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('expected_schema', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('avg_score_lift', sa.Float(), nullable=True),
    sa.Column('llm_model_used', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint("content_type IN ('explanation','scenario','quiz','dialogue')", name='ck_ci_type'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_skill', 'content_items', ['skill_id', 'content_type', 'difficulty_level'], unique=False)
    op.execute("CREATE INDEX idx_content_embedding ON content_items USING hnsw(embedding vector_cosine_ops);")
    op.create_table('employee_learning_states',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('mastery_confidence', sa.Float(), nullable=False),
    sa.Column('knowledge_gaps', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('misconception_map', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('learning_velocity', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint('current_score BETWEEN 0 AND 100', name='ck_els_score'),
    sa.CheckConstraint('mastery_level BETWEEN 0 AND 5', name='ck_els_mastery'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_els_employee_skill')
    )
    op.create_index('idx_els_employee', 'employee_learning_states', ['employee_id'], unique=False)
    op.create_index('idx_els_skill', 'employee_learning_states', ['skill_id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('session_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('mastery_reached', sa.Boolean(), nullable=False),
    sa.Column('path_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint("session_type IN ('baseline','learning','review')", name='ck_ls_type'),
    sa.CheckConstraint("status IN ('active','paused','completed','timed_out')", name='ck_ls_status'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastery_history',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('old_level', sa.Integer(), nullable=True),
    sa.Column('new_level', sa.Integer(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('override_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint("decision IN ('UPGRADE','MAINTAIN','DOWNGRADE')", name='ck_mh_decision'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_edges',
    sa.Column('prerequisite_id', sa.Uuid(), nullable=False),
    sa.Column('dependent_id', sa.Uuid(), nullable=False),
    sa.Column('edge_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dependent_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prerequisite_id', 'dependent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_edges')
    op.drop_table('mastery_history')
    op.drop_table('learning_sessions')
    op.drop_index('idx_els_skill', table_name='employee_learning_states')
    op.drop_index('idx_els_employee', table_name='employee_learning_states')
    op.drop_table('employee_learning_states')
    op.drop_index('idx_content_skill', table_name='content_items')
    op.execute("DROP INDEX IF EXISTS idx_content_embedding;")
    op.drop_table('content_items')
    op.drop_index('idx_ar_session', table_name='assessment_results')
    op.drop_index('idx_ar_employee_skill', table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index('idx_skills_competency', table_name='skills')
    op.drop_table('skills')
    op.drop_table('competencies')
    op.drop_index('idx_users_tenant', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
